# Only drop when inside the development environment
{{- if hasPrefix "devenv-" $.Release.Namespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "intake-db-migrate"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      name: "intake-db-migrate"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-database-schema-migration
        image: "localhost:5000/intake-db-workflows:local"
        command:
          - migrate.sh
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: {{ $.Values.development.mysql_database_user }}
        - name: MYSQL_PASSWORD
          value: {{ $.Values.development.mysql_database_password }}
{{- end }}
