apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $.Release.Name }}
spec:
  ports:
  - name: client
    port: {{ $.Values.intake_port }}
  selector:
    app: {{ $.Release.Name }}
