changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "January 02, 2006"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* [{{.Custom.JIRA}}](https://myjira.atlassian.net/browse/{{.Custom.JIRA}}) {{.Body}} ([PR #{{.Custom.PR}}](https://github.com/MattHodge/test-monorepo-auto/pull/{{.Custom.PR}}))'
kinds:
- label: Added
- label: Changed
- label: Deprecated
- label: Removed
- label: Fixed
- label: Security
newlines:
  afterChangelogHeader: 1
  beforeChangelogVersion: 1
  endOfVersion: 1
custom:
- key: JIRA
  type: string
  minLength: 5
replacements:
- path: k8s/Chart.yaml
  find: 'version: .*'
  replace: 'version: {{.VersionNoPrefix}}'
post:
- key: PR
  value: <<REPLACE_ME_WITH_PR>>
